# Refer version dependencies at 
# https://www.intel.com/content/www/us/en/developer/articles/system-requirements/intel-oneapi-dpcpp-system-requirements.html
c_compiler_version:     # [linux]
  - 7.5.0               # [linux]
cxx_compiler_version:   # [linux]
  - 7.5.0               # [linux]
binutils_version:       # [linux]
  - 2.30                # [linux]
